[G1] 2357 최솟값과 최댓값
joonparkhere/algorithm-study pull request #26
Opened 2021-07-25 20:57 UTC by HyeonjinChoi

## 대략적인 풀이
- 특정 구간에 대한 정보를 빠르게 탐색할 수 있는 세그먼트 트리를 이용한다.
- 원래 세그먼트 트리는 구간 합을 다루는 개념이지만, 본 문제에서는 최솟값과 최댓값을 구해야하므로
구간 합 대신에 구간 중 최솟값과 최댓값을 저장하는 트리를 생성한다.
- 구하고자 하는 답의 범위가 주어졌을 때, 재귀 방식을 통해 해당 범위에 대한 답을 구한다.

## 소요 메모리, 시간
- 11232KB, 164ms
  - 메모리 소요는 다소 컸지만, 시간은 백준에서 확인한 평균에 근접한 것으로 보인다.

2021-07-26 06:38 UTC, joonparkhere requested changes
`treeArr[]`를 사용하지 않도록 코드를 고쳐보는 것은 어떨까 합니다.

2021-07-26 06:38 UTC, joonparkhere commented on week04/assignment01/2357_최솟값과 최댓값_HyeonjinChoi.go
> +	} else {
위의 if문 안에 `scanInt()`로 입력받고 해당 값을 바로 `minTreeArr[]`와 `maxTreeArr[]`에 넣어주면, `treeArr[]`를 사용하지 않아도 되므로 메모리 절약이 될 것 같습니다.

2021-07-26 06:38 UTC, joonparkhere commented on week04/assignment01/2357_최솟값과 최댓값_HyeonjinChoi.go
> +		return int(math.Min(float64(leftMin), float64(rightMin))), int(math.Max(float64(leftMax), float64(rightMax)))
그냥 참고사항인데요, `math.Min()` 혹은 `math.Max()` 함수가 매우 많이 사용되다 보니 생각보다 시간 소요에 영향을 많이 끼치는 것 같더군요

저도 처음에 `math` 라이브러리를 사용했었다가, 별도로 구현해서 사용해보니 소요 시간에 약간의 개선이 있었습니다.

2021-08-05 04:15 UTC, HyeonjinChoi commented on week04/assignment01/2357_최솟값과 최댓값_HyeonjinChoi.go
> +	} else {
좋은 의견 감사합니다. 다음 풀이부터는 단순히 입력받기 위해 배열이 필요한 것인지 고민하는 습관을 가져보겠습니다.

2021-08-05 04:19 UTC, HyeonjinChoi commented on week04/assignment01/2357_최솟값과 최댓값_HyeonjinChoi.go
> +		return int(math.Min(float64(leftMin), float64(rightMin))), int(math.Max(float64(leftMax), float64(rightMax)))
좋은 의견 감사합니다. 수식 라이브러리를 사용할 때는 소요 시간을 잘 비교하면서 사용해야할 것 같습니다.

2021-08-05 07:23 UTC, joonparkhere approved these changes
수고하셨습니다

2021-08-05 10:00 UTC, merged