[P4] 1321 군인
joonparkhere/algorithm-study pull request #27
Opened 2021-07-25 20:57 UTC by HyeonjinChoi

## 대략적인 풀이
- 기본적인 세그먼트 트리의 특성을 이용하여 풀 수 있다.
- 가장 깊은 정점들에 각 부대의 군사 수를 저장하고 부모 정점은 자식 정점들의 합을 저장함으로써,
i번째 군인이 어느 부대에 속하는지 탐색하는데 용이하게 만들 수 있다.
- 각 구간의 값과 탐색하고자 하는 군인의 번호를 비교하며 자식 정점으로 넘어가고 
이를 반복하여 말단 정점에 도달했을 때의 index가 구하고 하는 부대의 번호이다.

## 소요 메모리, 시간
- 36568KB, 200ms
  - 메모리 및 시간 소요가 다소 큰 것으로 보인다.

2021-07-26 07:23 UTC, joonparkhere requested changes

2021-08-05 04:32 UTC, HyeonjinChoi commented on week04/assignment02/1321_군인_HyeonjinChoi.go
> +	midIdx := (startIdx + endIdx) / 2
좋은 의견 감사합니다. 거기까지 생각하지 못했었는데, 실행 흐름대로 구현해야 바람직하고 또한 코드리뷰 할 때도 수월하다는 것을 깨닫게 되었습니다.

2021-08-05 05:16 UTC, HyeonjinChoi commented on week04/assignment02/1321_군인_HyeonjinChoi.go
> +	treeArr[node] = treeArr[node*2] + treeArr[node*2+1]
네 알겠습니다. 함수 명을 결정하는데 좀 더 신경쓰도록 하겠습니다.

2021-08-05 05:16 UTC, HyeonjinChoi commented on week04/assignment02/1321_군인_HyeonjinChoi.go
> +	treeArr = make([]int, 100000001)
좋은 의견 감사합니다. 입력받은 부대 개수를 바탕으로 동적 할당하게 변경하였습니다.

2021-08-05 05:36 UTC, HyeonjinChoi commented on week04/assignment02/1321_군인_HyeonjinChoi.go
> +		treeArr[node] += num
좋은 의견 감사합니다. 파라미터는 적을수록 좋다는 것을 알면서도 편하게 코드를 작성하려다보니 발생한 문제인 것 같습니다.

2021-08-05 07:25 UTC, joonparkhere approved these changes
수고하셨습니다

2021-08-05 10:01 UTC, merged