[P4] 3653 영화 수집
joonparkhere/algorithm-study pull request #34
Opened 2021-08-01 14:53 UTC by HyeonjinChoi

## 대략적인 풀이
- treeArr[], dvdPos[] 이 두 가지 배열을 통해 문제를 해결한다.
- DVD 개수를 n, 테스트 횟수를 m 이라고 했을 때, treeArr[]의 말단 정점이 n+m 개 이상이 되도록 트리를 생성한다.
- treeArr[] 의 첫 m개의 원소를 비워두고, 이후 m+1부터 m+n개의 원소값을 1로 초기화한다.
- dvdPos[]의 원소값은 index 값과 매칭되는 각 DVD의 treeArr[]에서의 위치를 나타낸다.
ex) 1번 DVD : dvdPos[1] -> m + 1
- DVD를 보고 다시 쌓아올릴 경우에는 treeArr[m - 1] 부터 1씩 index를 감소시키며 저장한다.
테스트가 모두 끝났을 때는, treeArr[1] 값까지 저장되며 완료된다.

## 소요 메모리, 시간
- 23152KB, 328ms
  - 메모리 소요는 평균에 근접하지만 시간 소요가 약간 큰 것으로 보인다.

2021-08-01 18:58 UTC, joonparkhere requested changes

2021-08-01 18:58 UTC, joonparkhere commented on week04/assignment03/BOJ_3653_HyeonjinChoi.go
> +	initTree(1, 1, n+m)
`initTree()` 함수의 실질적인 역할 및 목적이 궁금합니다. 해당 함수를 호출하지 않아도 괜찮아 보이는데, 혹시 다른 문제가 생기나요?

2021-08-05 06:15 UTC, HyeonjinChoi commented on week04/assignment03/BOJ_3653_HyeonjinChoi.go
> +	initTree(1, 1, n+m)
단순히 초기화한다는 생각으로 구현한 것인데 어차피 `treeArr[]` 생성시 자동으로 초기화되기 때문에 
실질적으로 필요없는 함수인 것 같습니다. `initTree()`는 지우도록 하겠습니다.

성능 차원에서는 큰 차이가 없는 것으로 보입니다.

2021-08-05 07:26 UTC, joonparkhere approved these changes
수고하셨습니다

2021-08-05 10:01 UTC, merged