[G5] 1759 암호 만들기
joonparkhere/algorithm-study pull request #35
Opened 2021-08-01 14:53 UTC by HyeonjinChoi

## 대략적인 풀이
- 우선 입력받은 문자들을 사전순으로 정렬한다.
- `checkVowel[]`는 `inputArr[]`과 같은 인덱스의 문자를 비교하면서 모음에 해당될 경우,
true 값으로 갱신한다.
- `solve()`에서는 `position` 값을 이용하여 C 값과 같다면 출력하고, 아니라면 `inputArr[]`에서 문자를 하나씩 선택하며 암호를 완성한다.
재귀방식을 통해 `inputArr[]`의 문자를 통해 만들 수 있는 모든 경우의 수를 다룬다.
암호를 이루는 알파벳이 암호에서 증가하는 순서로 배열되었다는 조건이 있으므로,
`inputArr[]`에서 어떤 문자가 사용되었을 때 앞 인덱스의 문자가 다음에 오는 경우는 고려하지 않는다.
## 소요 메모리, 시간
- 912KB, 8ms
  - 메모리 및 시간 소요가 평균에 근접하는 것으로 보인다.

2021-08-01 19:18 UTC, joonparkhere requested changes

2021-08-01 19:18 UTC, joonparkhere commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +	inputArr = make([]byte, inputLen)
`answerArr`는 최댓값인 15로 초기화하고, `inputArr`는 입력 받은 값으로 초기화하고 있습니다.
초기화 방식을 통일하는 게 바람직합니다. 둘 다 최댓값으로 하거나 동적으로 초기화하면 좋을 것 같습니다.

2021-08-01 19:18 UTC, joonparkhere commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +		answerArr[position] = current
`current` 변수는 필요 없어 보입니다.

2021-08-01 19:18 UTC, joonparkhere commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +		if consonant >= 2 && vowel >= 1 {
문제 조건이 비밀번호 길이가 3이상 15이고, 모음은 1개 이상 그리고 자음은 2개 이상 포함해야 한다고 했습니다. 그러면 구하고자 하는 비밀번호에 모음 개수 + 2 가 비밀번호 길이보다 작거나 같다면 자음 개수는 알 필요 없이 조건을 충족시킬 수 있습니다.

그래서 위 if문 조건은 `vowel + 2 <= answerLen` 으로 바꿀 수 있을 것 같고, 더불어서 `solve()` 함수에서 `consonant` 파라미터를 제거할 수 있습니다.

2021-08-01 19:18 UTC, joonparkhere commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +	checkVowel = make([]bool, 26)
`checkVoewl`의 크기는 왜 26인가요? 코드 상에서는 `inputArr`와 크기가 같아도 무방해 보이는데, 다르게 설정하신 이유가 있을까요?

2021-08-05 09:16 UTC, HyeonjinChoi commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +	inputArr = make([]byte, inputLen)
코드를 수정하는 과정에서 놓친 부분인 것 같습니다. `answerArr`도 동적으로 초기화하도록 하겠습니다.

2021-08-05 09:16 UTC, HyeonjinChoi commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +		answerArr[position] = current
코드를 수정하는 과정에서 놓친 부분인 것 같습니다. 
다음 풀이부터는 제출하기 전에 다시 한 번 살펴보며 불필요한 부분들이 없는지 확인하도록 하겠습니다.

2021-08-05 09:19 UTC, HyeonjinChoi commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +		if consonant >= 2 && vowel >= 1 {
좋은 의견 감사합니다. 다만 말씀해주신 `vowel + 2 <= answerLen`만으로는 
모음 개수의 조건을 충족시키기 어려워 추가적으로 `vowel >= 1`이라는 조건도 넣어주었습니다.

수정 후 제출하였더니 성능상에서는 차이가 없었지만 지난번에 주신 의견과 마찬가지로
파라미터를 줄이는 습관을 들이도록 노력하겠습니다.

2021-08-05 09:21 UTC, HyeonjinChoi commented on week05/assignment01/BOJ_1759_HyeonjinChoi.go
> +	checkVowel = make([]bool, 26)
처음 `checkVowel`을 생성했을 때는 알파벳 개수를 생각하면서 크기를 정했습니다.
하지만 코드를 수정하면서 말씀해주신대로 `inputArr`와 크기가 같아도 무방하게 된 것 같습니다.
`checkVowel`의 크기도 동적으로 초기화하도록 변경하겠습니다.

2021-08-05 09:27 UTC, joonparkhere approved these changes
수고하셨습니다

2021-08-05 10:06 UTC, merged