[G1] 2213 트리의 독립집합
joonparkhere/algorithm-study pull request #61
Opened 2021-09-06 14:19 UTC by HyeonjinChoi

## 대략적인 풀이
- 다이나믹 프로그래밍을 통해 해결해야하는 문제이다.
- 두 가지 경우로 나눠서 생각해보면,
하나는 독립 집합 내에 어떤 노드가 존재할 경우 다음 노드는 존재하지 않는 것이고,
다른 하나는 독립 집합 내에 어떤 노드가 존재하지 않을 경우 다음 노드는 존재 여부가 상관없는 것이다.
이 때는 다음 노드가 존재하는 것과 존재하지 않는 것 중 큰 값을 선택한다.
- 위의 방식대로 dfs를 진행하고, 이후 트래킹을 진행한다.

## 소요 메모리, 시간
- 2696KB, 16ms

2021-09-07 23:19 UTC, joonparkhere requested changes

2021-09-07 23:19 UTC, joonparkhere commented on week09/assignment01/BOJ_2213_HyeonjinChoi.go
> +}
`Graph`와 `node`라는 변수명이 알맞지 않은 것 같습니다.

실제 코드에서는 `GraphArr`이라는 슬라이스로 그래프를 표현하고 있습니다. 하지만 일반적으로 `GraphArr`라고 하면 여러 개의 그래프가 저장된 배열이라고 생각합니다. 구조체 이름과 슬라이스 이름을 조금 더 알맞게 바꾸면 좋을 것 같습니다.

코드 상에서 `node`가 의미하는 바는 인접한 노드들이라고 생각하는데, 이 또한 변수명을 보다 구체적으로 정하면 좋을 것 같습니다.

2021-09-14 23:11 UTC, HyeonjinChoi commented on week09/assignment01/BOJ_2213_HyeonjinChoi.go
> +}
네 알겠습니다. 변수명의 의미가 애매모호하지 않도록 유의하겠습니다.

2021-09-14 23:30 UTC, joonparkhere approved these changes
수고하셨습니다

2021-09-19 15:10 UTC, merged