[G4] 1563 개근상
joonparkhere/algorithm-study pull request #62
Opened 2021-09-06 14:19 UTC by HyeonjinChoi

## 대략적인 풀이
- 날짜에 대한 정보, 지각한 횟수, 연속으로 결석한 회수에 대한 배열을 생성하여 다이나믹 프로그래밍을 진행한다.
- 배열에서 n번째 정보를 확인했을 때 개근상을 받을 수 있는 조건은 다음과 같다.
지각 : 0~1회, 연속 결석 : 0~2회
6가지 경우가 나오며 n-1번째 정보를 어떻게 연결시킬지 고려해야한다.
- 만약 n번째 정보가 지각 : 0, 연속 결석 : 0이라고 가정하면,
n-1번째 날은 지각은 당연히 없어야하지만 연속 결석은 0-2회 모두 가능하다.
만약 지각 : 0, 연속 결석 : 1이라고 가정하면,
지각은 마찬가지로 0이고 연속 결석은 0일 수밖에 없다.
만약 1-2이라면 n번째 날의 연속 결석 횟수가 0이 될 수 없기 때문이다.
- 위와 같은 방식으로 6가지 경우에 대해 모두 정리한다.

## 소요 메모리, 시간
- 1044KB, 8ms

2021-09-07 23:26 UTC, joonparkhere requested changes

2021-09-07 23:26 UTC, joonparkhere commented on week10/assignment01/BOJ_1563_HyeonjinChoi.go
> +	divisor = 1000000
`divisor`의 경우 이렇게 초기화하기 보다는 애초에 처음 선언할 때 `const divisor = 1000000` 이런 형태로 하는 것이 더 적합해 보입니다.

2021-09-07 23:26 UTC, joonparkhere commented on week10/assignment01/BOJ_1563_HyeonjinChoi.go
> +		}
`attendanceInfo` 3차원 배열에서 첫번째 인덱스만 동적이고, 두번째와 세번째 인덱스는 각각 2와 3으로 크기가 정해져있으므로 위처럼 반복할 필요없이 애초에 선언할 때 `var attendanceInfo [][2][3]int` 라고 하면 불필요한 코드를 줄일 수 있을 것 같습니다.

2021-09-14 23:17 UTC, HyeonjinChoi commented on week10/assignment01/BOJ_1563_HyeonjinChoi.go
> +	divisor = 1000000
좋은 조언 감사합니다.

2021-09-14 23:17 UTC, HyeonjinChoi commented on week10/assignment01/BOJ_1563_HyeonjinChoi.go
> +		}
저렇게 할 수 있는지 몰랐네요. 좋은 정보 감사합니다.

2021-09-14 23:31 UTC, joonparkhere approved these changes
수고하셨습니다

2021-09-19 15:12 UTC, merged