[G3] 1516 게임 개발
joonparkhere/algorithm-study pull request #63
Opened 2021-09-06 14:20 UTC by HyeonjinChoi

## 대략적인 풀이
- 방향 그래프가 있을 때 어떤 노드에 대해 들어오는 간선의 수인 진입차수 개념을 이용한다.
- 진입차수가 0인 노드부터 큐에 저장하며 bfs를 진행한다.
- 다음 노드의 진입차수를 1씩 빼주며 위의 과정을 반복한다.
- 만약 이전 노드의 개수가 2 이상이라면 하나의 노드가 건설되었더라도 다른 노드가 남아있기 때문에
시간을 계산할 때는 이전 노드의 시간 중 가장 큰 시간을 갖는 노드를 기준으로 진행한다.

## 소요 메모리, 시간
- 2328KB, 16ms

2021-09-07 23:37 UTC, joonparkhere requested changes

2021-09-07 23:37 UTC, joonparkhere commented on week10/assignment02/BOJ_1516_HyeonjinChoi.go
> +func (q *Queue) Peek() int {
일반적으로 자료구조 큐에서 사용되는 `Peek`의 역할은 가장 앞에 있는 요소를 반환하는 것만을 담당합니다.
앞에 있는 요소를 큐에서 제거하는 역할까지 담당하는 함수는 주로 `Remove` 혹은 `Dequeue` 등이 있습니다.

2021-09-14 23:20 UTC, HyeonjinChoi commented on week10/assignment02/BOJ_1516_HyeonjinChoi.go
> +func (q *Queue) Peek() int {
제가 실수한 것 같습니다. `Dequeue`가 맞습니다.

2021-09-14 23:32 UTC, joonparkhere approved these changes
수고하셨습니다

2021-09-19 15:12 UTC, merged