Week13 문제 제안
joonparkhere/algorithm-study pull request #76
Opened 2021-09-19 14:59 UTC by HyeonjinChoi

13주차 문제를 제안합니다.

1. https://www.acmicpc.net/problem/1647
2. https://www.acmicpc.net/problem/1238
3. https://www.acmicpc.net/problem/11779

2021-09-19 23:45 UTC, joonparkhere requested changes

2021-09-19 23:45 UTC, joonparkhere commented on README.md
> +| @HyeonjinChoi  | 3 | 3 |
이 PR에서는 양식만 추가하는 목적만 띠는 것이 어떨까요?
지각 제출과 미제출 횟수는 각 문제에 대한 Issue를 만든 후, 별도의 PR로 수정해주세요

2021-09-25 08:03 UTC, HyeonjinChoi commented on README.md
> +| @HyeonjinChoi  | 3 | 3 |
양식은 수정하고 제출 및 미제출에 대한 PR을 따로 올리겠습니다.
그런데 지각 제출에 대한 Issue는 이미 제출을 완료한 상태인데 굳이 생성하는 의미가 있을까요?

2021-09-25 08:14 UTC, joonparkhere commented on README.md
> +| @HyeonjinChoi  | 3 | 3 |
저랑 생각하는 과정이 다른 것 같습니다.

저는 각 주차에 풀기로 했지믄 못 푼 문제들에 대해서 Issue를 만들어 놓고, 나중에 지각 제출 혹은 풀이 포기할 때 Issue를 닫는 것으로 생각했습니다.

@HyeonjinChoi 님은 과정을 어떻게 생각하고 계신가요?

2021-09-25 08:19 UTC, HyeonjinChoi commented on README.md
> +| @HyeonjinChoi  | 3 | 3 |
저도 같은 생각인데 앞서 말씀하시기를 '지각 제출과 미제출 횟수는 각 문제에 대한 Issue를 만든 후, 별도의 PR로 수정해주세요' 라고
말씀하셔서 현재 제가 지각 제출한 과제까지 Issue를 만들라는 의도로 받아들였습니다. 그럼 Issue는 미제출한 문제들에 대해서만
작성하고 이어나가도록 하겠습니다.

같은 절차를 생각하고 있다고 받아들이고 진행해도 될까요?

2021-09-25 08:23 UTC, joonparkhere commented on README.md
> +| @HyeonjinChoi  | 3 | 3 |
넵 🐱

2021-09-25 08:23 UTC, joonparkhere approved these changes

2021-09-25 08:34 UTC, merged