최현진: week02 과제 제출
joonparkhere/algorithm-study pull request #8
Opened 2021-07-05 12:32 UTC by HyeonjinChoi

우선 17471번 문제 풀이를 제출합니다.
나머지 문제는 추가적으로 제출할 수 있도록 하겠습니다.

2021-07-05 23:33 UTC, joonparkhere requested changes
## pow(), absoluteValue()
- Q: 함수를 직접 구현하셨는데, math 라이브러리를 사용하지 않은 이유가 있을까요?

## findMinDiff()
- P1: 중간중간에 테스트 용도로 사용한 프린트문이 있습니다. 삭제해주세요
- P5: 더불어 프린트하면서 데이터를 확인하는 것도 괜찮지만 디버거 사용하는 습관을 들으시는 것도 좋을 것 같습니다. 실무 개발 시에는 콘솔에 프린트하기 보다 디버거를 많이 쓰는 것 같아요.
- P2: 이중 for문 중 두번째 for문에 의미없는 else{} 가 있습니다. 제거해도 괜찮지 않을까요?
- P5: 상관없을 수도 있는 얘기지만, 일부 실무 개발 팀에서는 - 그리고 클린 코드 서적에서는 - else 문 사용을 금기하는 곳도 있다고 합니다. 만약 `if {} else if {} else {}` 형태로 코드가 짜여 있으면 가독성도 안 좋고, 복잡한 조건이 여러 개 묶여 있다는 것이기 때문에 오로지 if {} 만 사용하도록 강제하는 경우도 있다고 해요.

## isConnected()
- P2: for 문 안에 의미없는 else {} 가 있습니다. 제거해도 괜찮지 않을까요?

P.S. 수고 많으셨습니다.

2021-07-06 14:09 UTC, HyeonjinChoi commented
## pow(), absoluteValue()
- Q: 함수를 직접 구현하셨는데, math 라이브러리를 사용하지 않은 이유가 있을까요?
> 잦은 형변환 때문에 정수형으로 구현을 해봤습니다. 
하지만 그렇게 가치있는 일은 아니기 때문에 다음부터는 math 라이브러리를 활용하도록 하겠습니다.

## findMinDiff()
- P1: 중간중간에 테스트 용도로 사용한 프린트문이 있습니다. 삭제해주세요
> 네 알겠습니다.
- P5: 더불어 프린트하면서 데이터를 확인하는 것도 괜찮지만 디버거 사용하는 습관을 들으시는 것도 좋을 것 같습니다. 실무 개발 시에는 콘솔에 프린트하기 보다 디버거를 많이 쓰는 것 같아요.
> 좋은 의견 감사합니다. 앞으로 디버거를 활용할 수 있도록 노력하겠습니다.
- P2: 이중 for문 중 두번째 for문에 의미없는 else{} 가 있습니다. 제거해도 괜찮지 않을까요?
- P5: 상관없을 수도 있는 얘기지만, 일부 실무 개발 팀에서는 - 그리고 클린 코드 서적에서는 - else 문 사용을 금기하는 곳도 있다고 합니다. 만약 `if {} else if {} else {}` 형태로 코드가 짜여 있으면 가독성도 안 좋고, 복잡한 조건이 여러 개 묶여 있다는 것이기 때문에 오로지 if {} 만 사용하도록 강제하는 경우도 있다고 해요.
> 같이 답변을 드리자면, 예전에 반환값이 존재하는 함수를 다룰 때 else {} 를 구현하지 않아 오류가 생겼던 경험이 있습니다.
그 때부터 습관적으로 의미가 없더라도 else {} 를 구현하는 것이 안정감 있다는 생각을 하게 되었던 것 같습니다.
하지만 가독성도 안 좋고 일부 실무 개발 팀에서 그런 의견을 가지고 있다고 한다면, 잘못된 습관으로 보이니 고치도록 하겠습니다.
## isConnected()
- P2: for 문 안에 의미없는 else {} 가 있습니다. 제거해도 괜찮지 않을까요?
> 네 제거하도록 하겠습니다.

그리고 추가적으로 16947번과 1967번 문제를 제출합니다.

2021-07-07 00:48 UTC, joonparkhere requested changes
# BOJ 16947

제가 전반적인 코드의 흐름을 이해하지 못했습니다. 오프라인 미팅 시에 추가적으로 물어보도록 하겠습니다.

## connectNode()

- Q: 역과 역 사이의 간선 정보들을 일반적인 배열이나 슬라이스가 아닌, `[]Stack` 구조에 기록하는 이유가 무엇인가요?

## checkCycle()

- P4: DFS 를 이용할 때 사이클 판별하는 흐름을 다시 한 번 공부해보시는 것을 추천드립니다. 현재 현진님의 풀이 방식은 여러므로 불필요한 반복이 더러 있고 흐름이 직관적이지 않은 것 같습니다.
- P3: `empty`라는 변수명은 불분명한 것 같습니다. 제가 이해한 바로는 인접한 역들 중에서 if 문의 조건을 충족하는 역이 존재하지 않을 때의 경우를 처리하기 위해 쓰이는 변수같은데, 로직을 조금 변경하면 사용하지 않아도 되는 변수인 거 같다고 생각합니다.

# BOJ 1967

이후의 풀이에서는 해당 풀이의 전반적인 흐름을 먼저 설명 후 각 메서드의 역할 설명이 이어지면 좋을 것 같습니다. 풀이의 큰 그림을 모른채로 함수 (메서드) 별 세부 역할을 이해하기는 어렵습니다. 어떻게 진행되는지 알아야 각 메서드가 하는 역할이 더욱 와닿을 것 같습니다.

위의 문제와 마찬가지로 오프라인 미팅에서 이해가 잘 안가는 몇가지 부분을 물어보도록 하겠습니다.

## Node

- P2: `inf`는 무엇의 약자인가요? 보통 inf 는 infinite 의 약자로 사용하는데 일반적인 경우와 다른 의미의 약자로 사용한다면 주석으로 설명을 덧붙이거나 약자를 사용하지 않는 것이 코드 이해함에 있어서 더 좋을 것 같습니다.

## connectNode()

- P4: 각 노드간의 인접 정보와 edge weight 정보를 기록하기 위해 `linkedArr` 와 `costArr` 를 별도로 선언해서 사용하는 것 같습니다. 그런데 커스텀 구조체로 Node 를 선언해서 사용한다면, Node 구조체에 위의 두 가지 정보를 담도록 하면 보다 낫지 않을까 생각합니다. 아래처럼 말이죠. 다만 이는 알고리즘의 효율성에는 영향을 끼치지 않으므로 참고만 해주시기 바랍니다.

  ```go
  type Node struct {
      adjacent int
      cost int
  }
  
  var arr [][]Node
  ```

## findFarthestNode()

- P2: `visitArr`와 `distance` 를 처음 사용하는 곳이 여기인데, 초기화하는 부분은 `connectNode()`에 위치합니다. 이렇게 되어있으면 제 3자가 코드를 읽을 때 "`visitArr`는 어디서 초기화되었길래 바로 사용하는 거지?" 혹은 "distance의 초기값은 뭐길래 바로 조건문에 쓰는거지?" 등의 의문이 생기고, 어쩔 수 없이 코드 전체를 훑어보며 어디서 초기화되었는 지 찾아야 합니다. 이는 코드 이해를 더 어렵게 만듭니다. 따라서 이러한 방식보다는 사용하는 곳에서 초기화를 하는 것이 더욱 적합해 보입니다.

2021-07-07 02:32 UTC, HyeonjinChoi commented
# BOJ 16947

제가 전반적인 코드의 흐름을 이해하지 못했습니다. 오프라인 미팅 시에 추가적으로 물어보도록 하겠습니다.
> 다음 풀이부터는 코드를 명료하게 작성할 수 있도록 노력하겠습니다.

## connectNode()

- Q: 역과 역 사이의 간선 정보들을 일반적인 배열이나 슬라이스가 아닌, `[]Stack` 구조에 기록하는 이유가 무엇인가요?
> 처음에는 2차원 슬라이스를 이용하여 간선 정보들을 저장했었습니다. 그런데 제가 문제를 헤매는 과정에서 2차원 슬라이스의 불필요한 공간이 메모리 낭비로 이어지는 것이 아닌가라는 생각을 하게 되었고, 그 과정에서 1차원 슬라이스를 멤버로 갖는 구조체를 떠올리게 되었습니다. 그런데 제가 이미 스택을 구현했기에 굳이 따로 타입을 구현할 필요가 없다는 생각을 해서 `[]Stack` 구조에 기록하게 되었습니다.

## checkCycle()

- P4: DFS 를 이용할 때 사이클 판별하는 흐름을 다시 한 번 공부해보시는 것을 추천드립니다. 현재 현진님의 풀이 방식은 여러므로 불필요한 반복이 더러 있고 흐름이 직관적이지 않은 것 같습니다.
> 다시 공부하여 부족한 부분을 채울 수 있도록 하겠습니다.
- P3: `empty`라는 변수명은 불분명한 것 같습니다. 제가 이해한 바로는 인접한 역들 중에서 if 문의 조건을 충족하는 역이 존재하지 않을 때의 경우를 처리하기 위해 쓰이는 변수같은데, 로직을 조금 변경하면 사용하지 않아도 되는 변수인 거 같다고 생각합니다.
> 승호님이 생각하신 의도대로 사용한 것이 맞습니다. 제가 전반적으로 풀이 방향을 잘못 잡아서 연쇄적으로 문제가 발생한 것 같습니다. 다음 풀이부터는 구현하기 전에 꼼꼼히 생각해보겠습니다.

# BOJ 1967

이후의 풀이에서는 해당 풀이의 전반적인 흐름을 먼저 설명 후 각 메서드의 역할 설명이 이어지면 좋을 것 같습니다. 풀이의 큰 그림을 모른채로 함수 (메서드) 별 세부 역할을 이해하기는 어렵습니다. 어떻게 진행되는지 알아야 각 메서드가 하는 역할이 더욱 와닿을 것 같습니다.

위의 문제와 마찬가지로 오프라인 미팅에서 이해가 잘 안가는 몇가지 부분을 물어보도록 하겠습니다.
> 구체적인 설명이 부족한 것도 문제이지만, 코드 자체가 명료하지 못하여 이해하는데 어려움이 있는 것 같습니다. 다음 풀이부터는 둘 다 신경써서 진행할 수 있도록 노력하겠습니다.

## Node

- P2: `inf`는 무엇의 약자인가요? 보통 inf 는 infinite 의 약자로 사용하는데 일반적인 경우와 다른 의미의 약자로 사용한다면 주석으로 설명을 덧붙이거나 약자를 사용하지 않는 것이 코드 이해함에 있어서 더 좋을 것 같습니다.
> information 을 줄여서 `info`로 사용한다는 것을 실수로 잘못 적었습니다. 그런데 `info`라는 변수명도 불분명할 수 있으니 다음부터는 직관적으로 이해할 수 있도록 변수명을 짓겠습니다.

## connectNode()

- P4: 각 노드간의 인접 정보와 edge weight 정보를 기록하기 위해 `linkedArr` 와 `costArr` 를 별도로 선언해서 사용하는 것 같습니다. 그런데 커스텀 구조체로 Node 를 선언해서 사용한다면, Node 구조체에 위의 두 가지 정보를 담도록 하면 보다 낫지 않을까 생각합니다. 아래처럼 말이죠. 다만 이는 알고리즘의 효율성에는 영향을 끼치지 않으므로 참고만 해주시기 바랍니다.

  ```go
  type Node struct {
      adjacent int
      cost int
  }
  
  var arr [][]Node
  ```
> 이 부분도 문제를 헤매는 과정에서 발생한 것 같습니다. 처음에는 말씀하신대로 구조체를 사용하여 코드를 작성했는데 계속 제한 시간을 초과하여 하나씩 바꿔보았습니다. `linkedArr`와 `costArr`를 별도로 선언한 이후 시점에서 해결책을 찾게 되었고, 이 부분은 문제가 아니었음을 알게 되었습니다. 알고리즘 효율성에는 영향을 끼치지 않겠지만 좀 더 코드를 명료하게 작성하기 위해서 다음 풀이부터는 신경쓰도록 노력하겠습니다.

## findFarthestNode()

- P2: `visitArr`와 `distance` 를 처음 사용하는 곳이 여기인데, 초기화하는 부분은 `connectNode()`에 위치합니다. 이렇게 되어있으면 제 3자가 코드를 읽을 때 "`visitArr`는 어디서 초기화되었길래 바로 사용하는 거지?" 혹은 "distance의 초기값은 뭐길래 바로 조건문에 쓰는거지?" 등의 의문이 생기고, 어쩔 수 없이 코드 전체를 훑어보며 어디서 초기화되었는 지 찾아야 합니다. 이는 코드 이해를 더 어렵게 만듭니다. 따라서 이러한 방식보다는 사용하는 곳에서 초기화를 하는 것이 더욱 적합해 보입니다.
> 저의 의도는 본격적인 풀이를 진행하기 전에 `connectNode()`에서 모든 세팅을 완료하는 것, 즉 모든 변수 및 배열 등의 초기화를 한 곳에서 진행하는 것이었습니다. 하지만 초기화 위치를 통해 사용의도를 파악할 수 있다는 생각을 하지 못했던 것 같습니다. 다음부터는 유의하겠습니다. 그리고 `distance` 값은 전역변수로서 `findFarthestNode()`가 재귀적으로 실행되면서 갱신되는 값이기 때문에 `findFarthestNode()`에서 처음 사용되더라도 초기화는 다른 곳에서 진행하는 것이 맞다고 생각합니다.

2021-07-07 02:55 UTC, joonparkhere approved these changes
수고 많으셨습니다.

2021-07-07 02:56 UTC, merged

2021-07-07 10:49 UTC, joonparkhere commented on week02/assignment01/16947_서울 지하철 2호선_HyeonjinChoi.go
> +		top := s.Peek()
[Test] 왜 Peek() 을 사용하시나요?